services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - my-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
      timeout: 3s
  backend:
    build:
      context: ./api
    depends_on:
      - db
    environment:
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_SERVER: db  
      DB_NAME: mydatabase
      DB_PORT: 5432
    ports:
      - "3000:3000"
    networks:
      - my-net
  frontend:
    build:
      context: ./ui
    depends_on:
      - backend
    ports:
      - "80:80"
    environment:
      API_URL: "http://backend:3000/"
    networks:
      - my-net
volumes:
  db_data:
networks:
  my-net:
